# Generated by Django 3.2.9 on 2021-12-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0006_auto_20211205_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=123)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_in', to='filmy.person')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starring', to='filmy.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='starring', through='filmy.Starring', to='filmy.Person'),
        ),
    ]
